### ISSUE TITLE
Symlinks are not supported

### ISSUE THREAD

**Issue by boreq** [boreq/eggplant#25]
Symlinks in the music directory are currently not supported as the implementation uses `filepath.Walk`. That function of the standard library [does not follow symlinks][explanation] to avoid loops. This means that symlinked directories will not be displayed by Eggplant.

Please react to this issue if this breaks your use case and possibly comment with a description of the problem.

[explanation]: https://github.com/golang/go/issues/4759#issuecomment-66074349

**Comment by coderobe** [comment]
This Breaks My Use Case
