### ISSUE TITLE
Numerical track listing is sorted wrong

### ISSUE THREAD

**Issue by coderobe** [boreq/eggplant#30]
The track list should respect numerical sorting
You can probably see the issue:
![Screenshot 2021-02-07 202524](https://user-images.githubusercontent.com/8442384/107157140-c499a280-6982-11eb-9d8e-072bf9cfe9f5.jpg)

**Comment by boreq** [comment]
Technically it is correct as the numbers are simply a part of the filename which is sorted lexicographically but I think it makes sense to improve this mechanism and make it smarter.
