### ISSUE TITLE
Eliminate dead vertical space on /browse view

### ISSUE THREAD

**Issue by coderobe** [boreq/eggplant#33]
Currently, about a quarter of the initial `/browse` page is used up by `💿 EₑG₉G₉PₚLₗAₐNₙTₜ`
![image](https://user-images.githubusercontent.com/8442384/107157643-73d77900-6985-11eb-878f-46eb05b0d40f.png)

How about moving this gigantic thing out of there, like so:
![image](https://user-images.githubusercontent.com/8442384/107157894-eb59d800-6986-11eb-9f44-4c8c69c8afd4.png)

or reducing the footprint of it in other ways?

**Comment by coderobe** [comment]
This change also works on the album view itself, turns out
![image](https://user-images.githubusercontent.com/8442384/107158168-8901d700-6988-11eb-848f-ad459546575d.png)

**Comment by boreq** [comment]
Eliminated about 12px of dead vertical space in boreq/eggplant-frontend@908b3c7a611b102d3c837143b504aefc69611885. :^)

**Comment by boreq** [comment]
Saved some more vertical space in all views in https://github.com/boreq/eggplant-frontend/commit/b6150a0adfad31a8d069d857247c497d80690581.

**Comment by boreq** [comment]
I think it would make sense to not display the album information at all if this is the root album and the thumbnail is not set.

**Comment by boreq** [comment]
Further cleanup in https://github.com/boreq/eggplant-frontend/commit/d6d1778f33511b300e43e1e13f2d2e0487abbd8f.

**Comment by boreq** [comment]
The album info is no longer displayed for the root album if it has no tracks and no thumbnail.
