### ISSUE TITLE
"I loaded 128 albums into eggplant on X and the main view is now Slow As Fuck"

### ISSUE THREAD

**Issue by boreq** [boreq/eggplant#35]

**Comment by coderobe** [comment]
I have a hunch, this *might* be due to the fact that the I/O load on my server is fairly high - if you do a lot of I/O, especially random seeks, perf suffers a lot.
If this is the case, perhaps cache most disk accesses (except for actual media file reads?)

**Comment by boreq** [comment]
It is possible that the situation was improved by 77ad735.

**Comment by coderobe** [comment]
![image](https://user-images.githubusercontent.com/8442384/107275866-9388a300-6a52-11eb-9346-825b6d6f3d72.png)

**Comment by boreq** [comment]
I am going to close this as any other slowness will be related to other issues and not this particular one, for example #39.
