### ISSUE TITLE
System media control integration

### ISSUE THREAD

**Issue by coderobe** [boreq/eggplant#37]
Right now, using system media controls (on windows in the screenshots, but this also applies to other OSes), all fields are defaulting - big chrome icon and generic website title - and the prev/next controls are disabled:
![image](https://user-images.githubusercontent.com/8442384/107160950-abe8b700-6999-11eb-9d82-62b58a8b3631.png)

This can be made fancier, the Spotify web player (open.spotify.com) manages this:
![image](https://user-images.githubusercontent.com/8442384/107160983-e05c7300-6999-11eb-84ec-4ccb8b9727f0.png)

**Comment by boreq** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaSession

I have no way to test this though.

**Comment by boreq** [comment]
Implemented everything apart from `setPositionState()` which doesn't actually seem to be supported by Windows or Chrome.

**Comment by boreq** [comment]
https://caniuse.com/mdn-api_mediasession
