### ISSUE TITLE
Create a proper long-running service package for Arch Linux

### ISSUE THREAD

**Issue by boreq** [boreq/eggplant#49]
Change the config to configure separate directories for:
- cache
- data
- music

Possible locations:
- `/var/cache/eggplant` (`CacheDirectory=`?)
  - `thumbnails`
  - `tracks`
- `/var/lib/eggplant` (`StateDirectory=`?)
  - `eggplant.bolt`
- `/etc/eggplant` (`ConfigurationDirectory=`?)
  - `config.toml`
- `/var/eggplant` (`StateDirectory=`?)
  - `Example Album`
    - `Example Song.mp3`

**Comment by coderobe** [comment]
Look into using systemd tmpfiles and sysusers for this

**Comment by boreq** [comment]
>man sysusers
>man tmpfiles
>sysusers.d and tmpfiles.d actually
>but if you just need it for the systemd servuce use DynamicUsers
>http://0pointer.net/blog/dynamic-users-with-systemd.html
>CacheDirectory=debuginfod
>etc
>you can also do read/write paths in the service
